# -*- coding: utf-8 -*-
"""ORF387 Final Project Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsIsuDFvUjOK1YBXH2im9WmRH2J2iMoT
"""

!pip install cartopy



from pathlib import Path
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

df = pd.read_csv(
    "/content/drive/MyDrive/Colab Notebooks/flightData.asc",
    sep="|",
    header=None,
    engine="python"
)

if df.iloc[:, -1].isna().all() or (df.iloc[:, -1] == "").all():
    df = df.iloc[:, :-1]

print(df.shape)
print(df.head())
df.columns = [
    "year", "month",
    "origin_airport", "origin_airport_id", "origin_state_fips", "origin_city",
    "dest_airport", "dest_airport_id", "dest_state_fips", "dest_city",
    "carrier", "carrier_id",
    "aircraft_group", "distance", "service_class",
    "unknown_1", "aircraft_type", "unknown_2",
    "departures_performed", "departures_scheduled",
    "seats", "payload", "freight", "mail",
    "unknown_3", "passengers",
    "source_field_1", "source_field_2"
]

numeric_cols = [
    "year", "month", "origin_airport_id", "origin_state_fips",
    "dest_airport_id", "dest_state_fips", "aircraft_group",
    "distance", "unknown_1", "aircraft_type", "unknown_2",
    "departures_performed", "departures_scheduled", "seats",
    "payload", "freight", "mail", "unknown_3", "passengers",
    "source_field_1", "source_field_2"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df["date"] = pd.to_datetime(
    df["year"].astype("Int64").astype(str) + "-" +
    df["month"].astype("Int64").astype(str).str.zfill(2) + "-01",
    errors="coerce"
)


df = df.dropna(subset=["origin_airport", "dest_airport"])
df = df[(df["origin_airport"] != "") & (df["dest_airport"] != "")]
df_no_self = df[df["origin_airport"] != df["dest_airport"]].copy()

print("\nRows after cleaning:", len(df_no_self))


route_edges = (
    df_no_self
    .groupby(["origin_airport", "dest_airport"], as_index=False)
    .agg(
        total_passengers=("passengers", "sum"),
        total_departures=("departures_performed", "sum"),
        total_seats=("seats", "sum"),
        avg_distance=("distance", "mean"),
        n_records=("origin_airport", "size")
    )
)

print("\nTop routes:")
print(route_edges.sort_values("total_passengers", ascending=False).head(10))


G = nx.DiGraph()

for _, row in route_edges.iterrows():
    G.add_edge(
        row["origin_airport"],
        row["dest_airport"],
        passengers=row["total_passengers"]
    )

print("\nGraph summary")
print("Nodes:", G.number_of_nodes())
print("Edges:", G.number_of_edges())

out_strength = dict(G.out_degree(weight="passengers"))
in_strength = dict(G.in_degree(weight="passengers"))

betweenness = nx.betweenness_centrality(G, normalized=True)

pagerank = nx.pagerank(G, weight="passengers")

metrics = pd.DataFrame({
    "airport": list(G.nodes())
})

metrics["out_passengers"] = metrics["airport"].map(out_strength).fillna(0)
metrics["in_passengers"] = metrics["airport"].map(in_strength).fillna(0)
metrics["total_passengers"] = metrics["out_passengers"] + metrics["in_passengers"]
metrics["betweenness"] = metrics["airport"].map(betweenness).fillna(0)
metrics["pagerank"] = metrics["airport"].map(pagerank).fillna(0)

print("\nTop airports by traffic:")
print(metrics.sort_values("total_passengers", ascending=False).head(15))

top25 = metrics.sort_values("total_passengers", ascending=False).head(25)

plt.figure(figsize=(10, 7))
plt.barh(top25["airport"], top25["total_passengers"])
plt.gca().invert_yaxis()
plt.xlabel("Total passenger flow")
plt.title("Top 25 airports")
plt.show()

top25 = (
    metrics.sort_values("total_passengers", ascending=False)
    .head(25)["airport"]
    .tolist()
)

edges_top25 = route_edges[
    route_edges["origin_airport"].isin(top25) &
    route_edges["dest_airport"].isin(top25)
]

matrix = edges_top25.pivot_table(
    index="origin_airport",
    columns="dest_airport",
    values="total_passengers",
    fill_value=0
)

matrix = matrix.reindex(index=top25, columns=top25, fill_value=0)

print(matrix)

print("\nTop airports by betweenness:")
betweenness_table = metrics.sort_values("betweenness", ascending=False).head(25)
print(betweenness_table[["airport", "betweenness", "total_passengers", "pagerank"]])
betweenness_table.to_csv("top25_betweenness.csv", index=False)

top25_airports = (
    metrics.sort_values("total_passengers", ascending=False)
    .head(25)["airport"]
    .tolist()
)

G_top25 = G.subgraph(top25_airports).copy()

print("\nTop-25 subgraph summary")
print("Nodes:", G_top25.number_of_nodes())
print("Edges:", G_top25.number_of_edges())

top25_metric_map = metrics.set_index("airport")
node_sizes = [
    top25_metric_map.loc[node, "total_passengers"] / 50000
    for node in G_top25.nodes()
]

edge_widths = [
    max(G_top25[u][v]["passengers"] / 200000, 0.5)
    for u, v in G_top25.edges()
]

plt.figure(figsize=(14, 10))
pos = nx.spring_layout(G_top25, k=1.2, seed=42)

nx.draw_networkx_nodes(
    G_top25,
    pos,
    node_size=node_sizes,
    alpha=0.8
)

nx.draw_networkx_edges(
    G_top25,
    pos,
    width=edge_widths,
    alpha=0.35,
    arrows=True,
    arrowsize=12
)

nx.draw_networkx_labels(
    G_top25,
    pos,
    font_size=10
)

plt.title("Top 25 Airports Network")
plt.axis("off")
plt.tight_layout()
plt.show()

from google.colab import drive
drive.mount('/content/drive')

airport_coords = {
    "DEN": (39.8561, -104.6737),
    "DFW": (32.8998, -97.0403),
    "ORD": (41.9742, -87.9073),
    "LAX": (33.9416, -118.4085),
    "ATL": (33.6407, -84.4277),
    "SEA": (47.4502, -122.3088),
    "LAS": (36.0840, -115.1537),
    "PHX": (33.4342, -112.0116),
    "MCO": (28.4312, -81.3081),
    "CLT": (35.2140, -80.9431),
    "SFO": (37.6213, -122.3790),
    "JFK": (40.5, -71.5),
    "EWR": (39, -73),
    "BOS": (42.3656, -71.0096),
    "IAH": (29.9902, -95.3368),
    "LGA": (41, -73),
    "MIA": (25.7959, -80.2870),
    "MSP": (44.8848, -93.2223),
    "PHL": (39.8744, -75.2424),
    "DCA": (38, -77.5),
    "DTW": (42.2162, -83.3554),
    "FLL": (26.0726, -80.1527),
    "SLC": (40.7899, -111.9791),
    "SAN": (32.7338, -117.1933),
    "AUS": (30.1975, -97.6664),
}
#"JFK": (40.6413, -73.7781),
#"EWR": (40.6895, -74.1745),
#"DCA": (38.8512, -77.0402),

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

top_airports = (
    metrics.sort_values("total_passengers", ascending=False)
    .head(25)
    .copy()
)

top_airports["lat"] = top_airports["airport"].map(lambda x: airport_coords.get(x, (None, None))[0])
top_airports["lon"] = top_airports["airport"].map(lambda x: airport_coords.get(x, (None, None))[1])
top_airports = top_airports.dropna(subset=["lat", "lon"])

mapped_codes = set(top_airports["airport"])

edges_top = route_edges[
    route_edges["origin_airport"].isin(mapped_codes) &
    route_edges["dest_airport"].isin(mapped_codes)
]

fig = plt.figure(figsize=(15, 10))
ax = plt.axes(projection=ccrs.PlateCarree())

ax.set_extent([-125, -66, 24, 50], crs=ccrs.PlateCarree())
ax.add_feature(cfeature.LAND)
ax.add_feature(cfeature.COASTLINE)
ax.add_feature(cfeature.BORDERS)
ax.add_feature(cfeature.STATES, linewidth=0.5)

weights = edges_top["total_passengers"]
min_w = weights.min()
max_w = weights.max()

def scale_width(w):
    if max_w == min_w:
        return 2
    return 0.5 + 4.5 * (w - min_w) / (max_w - min_w)

for _, row in edges_top.iterrows():
    lat1, lon1 = airport_coords[row["origin_airport"]]
    lat2, lon2 = airport_coords[row["dest_airport"]]

    ax.plot(
        [lon1, lon2],
        [lat1, lat2],
        color="black",
        alpha=0.35,
        linewidth=scale_width(row["total_passengers"]),
        zorder=1,
        transform=ccrs.PlateCarree()
    )

ax.scatter(
    top_airports["lon"],
    top_airports["lat"],
    s=top_airports["total_passengers"] / 300000,
    color="red",
    alpha=0.8,
    zorder=2,
    transform=ccrs.PlateCarree()
)

for _, row in top_airports.iterrows():
    ax.text(
        row["lon"] + 0.3,
        row["lat"] + 0.3,
        row["airport"],
        fontsize=10,
        weight="bold",
        color="#00FFFF",  # neon blue / cyan
        zorder=3,
        transform=ccrs.PlateCarree()
    )
plt.title("Top Airports Network on US Map")
plt.show()

def max_shortest_path_length(G):
    lengths = dict(nx.all_pairs_shortest_path_length(G))

    max_dist = 0

    for u in G.nodes():
        for v in G.nodes():
            if u == v:
                continue

            if v not in lengths[u]:
                return float("inf")

            max_dist = max(max_dist, lengths[u][v])

    return max_dist

def one_connection_property(G):
    return max_shortest_path_length(G) <= 2

G_top25 = G.subgraph(top25).copy()

G_test = G_top25.copy()

removed_edges = []

edges_sorted = sorted(
    G_test.edges(data=True),
    key=lambda x: x[2].get("passengers", 0)
)

for i, (u, v, data) in enumerate(edges_sorted):
    if i % 10 == 0:
        print(f"Checking edge {i}/{len(edges_sorted)}")

    G_temp = G_test.copy()
    G_temp.remove_edge(u, v)

    if one_connection_property(G_temp):
        G_test.remove_edge(u, v)
        removed_edges.append((u, v, data.get("passengers", 0)))

print("Original top-25 edges:", G_top25.number_of_edges())
print("Remaining edges:", G_test.number_of_edges())
print("Edges removed:", len(removed_edges))
print("Maximum distance after removal:", max_shortest_path_length(G_test))

removed_df = pd.DataFrame(
    removed_edges,
    columns=["origin", "destination", "passengers"]
)

print(removed_df.sort_values("passengers").head(20))

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import pandas as pd
top_airports = (
    metrics.sort_values("total_passengers", ascending=False)
    .head(25)
    .copy()
)

top_airports["lat"] = top_airports["airport"].map(lambda x: airport_coords.get(x, (None, None))[0])
top_airports["lon"] = top_airports["airport"].map(lambda x: airport_coords.get(x, (None, None))[1])
top_airports = top_airports.dropna(subset=["lat", "lon"])

edges_top_removed = []

for u, v, data in G_test.edges(data=True):
    edges_top_removed.append({
        "origin_airport": u,
        "dest_airport": v,
        "total_passengers": data.get("passengers", 0)
    })

edges_top_removed = pd.DataFrame(edges_top_removed)


for u, v, data in G_top25.edges(data=True):
    if not G_test.has_edge(u, v):
        removed_edges_to_plot.append({
            "origin_airport": u,
            "dest_airport": v,
            "total_passengers": data.get("passengers", 0)
        })

removed_edges_to_plot = pd.DataFrame(removed_edges_to_plot)

fig = plt.figure(figsize=(15, 10))
ax = plt.axes(projection=ccrs.PlateCarree())

ax.set_extent([-125, -66, 24, 50], crs=ccrs.PlateCarree())
ax.add_feature(cfeature.LAND)
ax.add_feature(cfeature.COASTLINE)
ax.add_feature(cfeature.BORDERS)
ax.add_feature(cfeature.STATES, linewidth=0.5)

weights = edges_top_removed["total_passengers"]

min_w = weights.min()
max_w = weights.max()

def scale_width(w):
    if max_w == min_w:
        return 2
    return 0.5 + 4.5 * (w - min_w) / (max_w - min_w)

for _, row in edges_top_removed.iterrows():
    lat1, lon1 = airport_coords[row["origin_airport"]]
    lat2, lon2 = airport_coords[row["dest_airport"]]

    ax.plot(
        [lon1, lon2],
        [lat1, lat2],
        color="black",
        alpha=0.45,
        linewidth=scale_width(row["total_passengers"]),
        zorder=1,
        transform=ccrs.PlateCarree()
    )
ax.scatter(
    top_airports["lon"],
    top_airports["lat"],
    s=top_airports["total_passengers"] / 300000,
    color="red",
    alpha=0.8,
    zorder=3,
    transform=ccrs.PlateCarree()
)

for _, row in top_airports.iterrows():
    ax.text(
        row["lon"] + 0.3,
        row["lat"] + 0.3,
        row["airport"],
        fontsize=10,
        weight="bold",
        color="#00FFFF",
        zorder=4,
        transform=ccrs.PlateCarree(),
        bbox=dict(
            facecolor="black",
            edgecolor="none",
            boxstyle="round,pad=0.2",
            alpha=0.8
        )
    )

plt.title("Top 25 Airport Network After Greedy Edge Removal")
plt.show()

G_top25 = G.subgraph(top25).copy()

def component_stats(G_current):
    UG = G_current.to_undirected()

    if UG.number_of_nodes() == 0:
        return {
            "largest_component_frac": 0,
            "num_components": 0,
            "avg_shortest_path": float("inf"),
            "remaining_passengers": 0
        }

    components = list(nx.connected_components(UG))
    largest_cc = max(components, key=len)
    H = UG.subgraph(largest_cc).copy()

    if H.number_of_nodes() > 1:
        avg_path = nx.average_shortest_path_length(H)
    else:
        avg_path = 0

    remaining_passengers = sum(
        data.get("passengers", 0)
        for _, _, data in G_current.edges(data=True)
    )

    return {
        "largest_component_frac": len(largest_cc) / UG.number_of_nodes(),
        "num_components": len(components),
        "avg_shortest_path": avg_path,
        "remaining_passengers": remaining_passengers
    }


def run_edge_attack(G_base, edge_order, label):
    G_current = G_base.copy()
    results = []

    original_passengers = sum(
        data.get("passengers", 0)
        for _, _, data in G_base.edges(data=True)
    )

    stats = component_stats(G_current)
    results.append({
        "strategy": label,
        "edges_removed": 0,
        "largest_component_frac": stats["largest_component_frac"],
        "num_components": stats["num_components"],
        "avg_shortest_path": stats["avg_shortest_path"],
        "remaining_passenger_frac": stats["remaining_passengers"] / original_passengers
    })

    for k, (u, v) in enumerate(edge_order, start=1):
        if G_current.has_edge(u, v):
            G_current.remove_edge(u, v)

        stats = component_stats(G_current)

        results.append({
            "strategy": label,
            "edges_removed": k,
            "largest_component_frac": stats["largest_component_frac"],
            "num_components": stats["num_components"],
            "avg_shortest_path": stats["avg_shortest_path"],
            "remaining_passenger_frac": stats["remaining_passengers"] / original_passengers
        })

    return pd.DataFrame(results)

edges_by_passengers = sorted(
    G_top25.edges(data=True),
    key=lambda x: x[2].get("passengers", 0),
    reverse=True
)

edges_by_passengers = [
    (u, v)
    for u, v, data in edges_by_passengers
]

edge_betweenness = nx.edge_betweenness_centrality(
    G_top25,
    normalized=True,
    weight=None
)

edges_by_betweenness = sorted(
    edge_betweenness.items(),
    key=lambda x: x[1],
    reverse=True
)

edges_by_betweenness = [
    (u, v)
    for (u, v), score in edges_by_betweenness
]


print("Top-25 nodes:", G_top25.number_of_nodes())
print("Top-25 directed edges:", G_top25.number_of_edges())
print("Passenger attack edges:", len(edges_by_passengers))
print("Betweenness attack edges:", len(edges_by_betweenness))

passenger_attack_df = run_edge_attack(
    G_top25,
    edges_by_passengers,
    "Highest passenger routes removed first"
)

betweenness_attack_df = run_edge_attack(
    G_top25,
    edges_by_betweenness,
    "Highest directed-betweenness routes removed first"
)

attack_df = pd.concat(
    [passenger_attack_df, betweenness_attack_df],
    ignore_index=True
)

print(attack_df.head())
print(attack_df.tail())
plt.figure(figsize=(9, 6))

for strategy, group in attack_df.groupby("strategy"):
    plt.plot(
        group["edges_removed"],
        group["largest_component_frac"],
        label=strategy
    )

plt.xlabel("Number of Directed Edges Removed")
plt.ylabel("Largest Component Fraction")
plt.title("Top-25 Airport Subgraph: Structural Resilience")
plt.legend()
plt.show()

plt.figure(figsize=(9, 6))

for strategy, group in attack_df.groupby("strategy"):
    plt.plot(
        group["edges_removed"],
        group["avg_shortest_path"],
        label=strategy
    )

plt.xlabel("Number of Directed Edges Removed")
plt.ylabel("Average Shortest Path Length")
plt.title("Top-25 Airport Subgraph: Path Efficiency After Edge Removal")
plt.legend()
plt.show()

plt.figure(figsize=(9, 6))

for strategy, group in attack_df.groupby("strategy"):
    plt.plot(
        group["edges_removed"],
        group["remaining_passenger_frac"],
        label=strategy
    )

plt.xlabel("Number of Directed Edges Removed")
plt.ylabel("Fraction of Passenger Flow Remaining")
plt.title("Top-25 Airport Subgraph: Passenger Flow Remaining")
plt.legend()
plt.show()

betweenness_nodes = nx.betweenness_centrality(
    G_top25,
    normalized=True,
    weight=None  # unweighted shortest paths
)

betweenness_df = pd.DataFrame({
    "airport": list(betweenness_nodes.keys()),
    "betweenness": list(betweenness_nodes.values())
})

betweenness_df = betweenness_df.sort_values(
    "betweenness",
    ascending=False
)

print("\nTop-25 airports by betweenness centrality:")
print(betweenness_df)